export enum chatEnum {
  error = "error-message",
  joinRoom = "join-room",
  joined = "joined-user",
  disconnect = "disconnect",
  sendMessage = "sendMessage",
  receive = "receive_message",
  joinmeet = "join-meet",
  userConnected = "userConnected",
  signal = "signal",
  videoState = "changevidostate",
  audioState = "audiostatechange",
  message = "message",
  leaveRoom = "leave-room",
  // joinRoom = 'joinChat',
  // joinmeet = 'joinmeet',
  // sendMessage = 'sendMessage',
  // receive = 'message',
  // joined = 'joined',
  // userConnected = 'userConnected',
  // videoState = 'videoState',
  // audioState = 'audioState',
  // error = 'error',
  // signal = 'signal',
}