export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    USER_IS_BLOKED: "User is Blocked",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, try again",
    OTP_NOT_FOUND: "Otp not found",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully",
    EMAIL_EXIST: "Email already exist",
    INVALID_EMAIL: "Invalid email address",
    OTP_RESEND_SUCCESS: "Otp resent successfully",
    LOGIN_SUCCESS: "Logged in successfully",
    LOGOUT_SUCCESS: "Logged out successfully",
    INVALID_PASSWORD: "Invalid password",
    EMAIL_SENT_SUCCESS: "Email sent successfully", 
    RESET_PASS_LINK: "Password reset link sent to your email",
    PASSWORD_RESET_SUCCESS: "Password reset successfully",
    TOKEN_EXPIRED: "Token expired",
    USER_ALREADY_EXIST_WITH_PASSWORD: "User already exist with password",
    UNAUTHORIZED : "Unauthorized Request",
    TOKEN_GENERATED_SUCCESS : "Token Regenerating Successfull",
    DATA_FETCHING_SUCCESSFULL : "Data fetched successfully",
    INVALID_REQUEST_DATA : "Invalid request data",

    GENERATING_FITNESS_PLAN_SUCCESSFULL : "Creating user fitness plan successfull",
    FAILED_TO_GENERATE_FITNESS_PLAN :  "Failed to generate fitness plan",
    FAILED_TO_CREATE_OR_UPDATE_PERSONALIZATION:"Failed to create or update personalization",
    FAILED_TO_GENERATE_WORKOUT_PLAN : "Failed to create workout plan",
    FAILED_TO_GENERATE_DIET_PLAN : "Failed to create diet plan",

    //workouts respnse messages
    WORKOUTS_FETCHED_SUCCESSFULL: "Workouts fetched successfully",
    FAILED_TO_FETCH_BASIC_FITNESS_PLAN: "Failed to fetch basic fitness plan",
    FAILED_TO_FETCH_WORKOUTS: "Failed to fetch workouts",
    FAILED_TO_FETCH_DIET_PLAN: "Failed to fetch diet plan",
    FAILED_TO_FETCH_WEEK_COMPLETION_STATUS: "Failed to fetch week completion status",
    WORKOUT_NOT_FOUND: "Workout not found",
    WEEK_COMPLETION_STATUS_UPDATED: "Week completion status updated successfully",
    FAILED_TO_UPDATE_WEEK_COMPLETION_STATUS: "Failed to update week completion status",
    FAILED_TO_UPDATE_DAY_COMPLETION_STATUS: "Failed to update day completion status",
    FAILED_TO_FETCH_WORKOUT_REPORT: "Failed to fetch workout report",
    FAILED_TO_GENERATE_NEXT_WEEK_WORKOUT: "Failed to generate next week workout",

    // weekly challenges response messages
    WEEKLY_CHALLENGES_FETCHED: "Weekly challenges fetched successfully",
    FAILED_TO_FETCH_WEEKLY_CHALLENGES: "Failed to fetch weekly challenges",
    USER_ALREADY_JOINED_CHALLENGE: "User already joined this challenge",
    FAILED_TO_JOIN_WEEKLY_CHALLENGE: "Failed to join weekly challenge",
    FAILED_TO_FETCH_USER_WEEKLY_CHALLENGE: "Failed to fetch user weekly challenge",
    FAILED_TO_UPDATE_USER_WEEKLY_CHALLENGE: "Failed to update user weekly challenge",
};