export const HttpResponse = {
    SERVER_ERROR: "Internal server error",
    USER_EXIST: "User already exist",
    PAGE_NOT_FOUND: "Route not found",
    USER_NOT_FOUND: "User not found",
    PASSWORD_INCORRECT: "Incorrect password, try again",
    NO_TOKEN: "Token not provided",
    OTP_INCORRECT: "Incorrect otp, try again",
    OTP_NOT_FOUND: "Otp not found",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_CREATION_FAILED: "User creation failed",
    USER_CREATION_SUCCESS: "User created successfully",
    GOOGLE_LOGIN_SUCCESS: "Logged in with Google successfully",
    EMAIL_EXIST: "Email already exist",
    INVALID_EMAIL: "Invalid email address",
    OTP_RESEND_SUCCESS: "Otp resent successfully",
    LOGIN_SUCCESS: "Logged in successfully",
    LOGOUT_SUCCESS: "Logged out successfully",
    INVALID_PASSWORD: "Invalid password",
    EMAIL_SENT_SUCCESS: "Email sent successfully", 
    RESET_PASS_LINK: "Password reset link sent to your email",
    PASSWORD_RESET_SUCCESS: "Password reset successfully",
    TOKEN_EXPIRED: "Token expired",
    USER_ALREADY_EXIST_WITH_PASSWORD: "User already exist with password",
    UNAUTHORIZED : "Unauthorized Request",
    TOKEN_GENERATED_SUCCESS : "Token Regenerating Successfull"
};